# Streamlit konfiguration för att undvika konflikt med PyTorch
# "fileWatcherType = none" löser fel som orsakas av torch.classes i vissa miljöer
# t.ex. "RuntimeError: Tried to instantiate class __path__"
[server]
runOnSave = false
fileWatcherType = "none"